ops: epetra: revise rank-1 update
Pressio/pressio pull request #537
Opened 2023-01-17 09:47 UTC by mzuzek

Contents:
- [x] revised overload constraints 
- [x] added extent check
- [x] added explicit type casting for coefficients
- [x] fixed NaN injection through zero coefficients and added relevant unit test

refs #448

2023-01-17 09:49 UTC, mzuzek commented
@fnrizzi 

Here in Epetra all coefficients have the same `scalar_t` type.
Would you prefer to allow different coefficient types `a_Type`, `b_Type`, etc. like in [Eigen](https://github.com/Pressio/pressio/blob/develop/include/pressio/ops/eigen/ops_rank1_update.hpp#L190-L194) ?

2023-01-17 09:59 UTC, mzuzek commented
@fnrizzi 

Here in Epetra all vectors have the same `T` type.
Would you prefer to allow different vector types `T1`, `T2`, etc. like in [Eigen](https://github.com/Pressio/pressio/blob/develop/include/pressio/ops/eigen/ops_rank1_update.hpp#L190-L194) ?

2023-01-17 10:28 UTC, fnrizzi commented
> @fnrizzi
> 
> Here in Epetra all coefficients have the same `scalar_t` type. Would you prefer to allow different coefficient types `a_Type`, `b_Type`, etc. like in [Eigen](https://github.com/Pressio/pressio/blob/develop/include/pressio/ops/eigen/ops_rank1_update.hpp#L190-L194) ?

yes please!

2023-01-17 10:29 UTC, fnrizzi commented
> 

yes, we should have separate types T1, T2, etc

2023-01-19 10:19 UTC, fnrizzi commented on tests/functional_small/ops/ops_epetra_vector.cc
> +    auto nan = pressio::ops::clone(*myVector_);
`nan -> vecOfNan`

2023-01-19 10:19 UTC, fnrizzi requested changes
see comment

2023-01-19 14:52 UTC, mzuzek commented on tests/functional_small/ops/ops_epetra_vector.cc
> +    auto nan = pressio::ops::clone(*myVector_);
fixed on 8da25625f132b7bb87b2d1d6423961a8826d2078

2023-01-20 07:54 UTC, fnrizzi approved these changes

2023-01-20 07:54 UTC, merged

2023-01-20 16:43 UTC, mzuzek commented
thanks @mzuzek for your review and comments!