ops: tpetra: revise rank-2 `update`
Pressio/pressio pull request #546
Opened 2023-01-23 20:40 UTC by mzuzek

ops: tpetra: revise rank-2 `update`Contents:
- [x] revised overload constraints
- [x] added extent checks
- [x] added explicit type casting for coefficients
- [x] fixed NaN injection bug and added related unit tests
- [x] fixed no-alpha overload and added related unit tests

refs #449

2023-01-25 10:16 UTC, fnrizzi commented on include/pressio/ops/tpetra/ops_multi_vector_update.hpp
> +  scalar_t b_{b};
`const scalar_t`

2023-02-01 17:56 UTC, mzuzek commented on include/pressio/ops/tpetra/ops_multi_vector_update.hpp
> +  scalar_t b_{b};
fixed with 548ca39686a5f6afe804e35976cc83c40096cfc2

2023-02-03 14:47 UTC, fnrizzi commented on include/pressio/ops/tpetra/ops_multi_vector_update.hpp
> +  pressio::ops::update(mv, zero, mv1, b);
I would either use `::pressio::ops::update` or i would just call `update()`

2023-02-03 14:47 UTC, fnrizzi requested changes
see comment

2023-02-03 20:11 UTC, mzuzek commented on include/pressio/ops/tpetra/ops_multi_vector_update.hpp
> +  pressio::ops::update(mv, zero, mv1, b);
thanks, fixed on c9d03ba4624d9b19dfb5e0acd5954ee00cee5715

2023-02-05 08:47 UTC, fnrizzi commented on tests/functional_small/ops/ops_tpetra_multi_vector.cc
> +    auto a = ::pressio::ops::clone(*myMv_);
i was not worried about the namespace in the tests since here this is a single executable with nothing else but this is fine too!

2023-02-05 08:47 UTC, fnrizzi approved these changes

2023-02-05 08:47 UTC, merged

2023-02-07 12:06 UTC, mzuzek commented
@fnrizzi thank you for the review and your comments!